### ISSUE TITLE
License under CC0, not AGPL License

### ISSUE THREAD

**Issue by benbalter** [BenKallos/legislation#2]
The project is [currently licensed under the AGPL license](https://github.com/BenKallos/legislation/blob/master/LICENSE). There are three reasons this isn't the best license for the project:

First, the AGPL license is a software license. It's intended to facilitate the distribution of software, and as such, has references to things like technical documentation, source code versus binary distributions, static versus dynamic linking, all things which do not apply in this case.

Second, the AGPL is the most restrictive copyleft license in the software world. Not only does it use commercial copyright law to prohibit otherwise valid uses, unlike most other GPL-family licenses, it goes so far as to include use within a service. Excerpting the proposed legislation on a blog or news website can be enough to trigger the copyleft redistribution requirements, and would "poison" the site, requiring the publisher to license their completely unrelated works under the same license (or refuse to quote the proposed legislation).

Finally, as proposed legislation, it's imperative to facilitating a healthy democratic dialog that both supporters and opponents be able to cite the legislation, without stringent attribution or share alike requirements, not to mention, if codified into law, should not be encumbered by commercial copyright restrictions.

Instead, licensing the proposed legislation under [a cc0](https://creativecommons.org/about/cc0) would be a better fit and would be in line with [similiar efforts](http://project-open-data.github.io).

/cc @joshdata, @konklone who may also have strong opinions on the issue.

**Comment by konklone** [comment]
Big :+1: from me to all of the above, especially given the nature of this work as proposed legal documents.

**Comment by fedex1** [comment]
I agree that this project is a wonderful idea.  Please promote it.  For example, I see legislation proposed modifying the New York City Charter but there is no link or reference to the actual New York City Charter.  It would be helpful if the legislation included references to what it was modifying.

Also it would nice, if all legislation was in a source code repository and the revision history was kept in a public place for all to access and see.

**Comment by BenKallos** [comment]
Thank you @benbalter  for the comment on the license. While I understand the concern regarding the AGPL license and am a supporter of no rights reserved, for the purposes of this project, I believe we have selected the appropriate license.

**Comment by BenKallos** [comment]
@fedex1 I agree with your comment and co-sponsored a law to put the law online and as a result the City's law will be online. In the meantime I've posted the City Charter and Laws online at BenKallos.com/Law

**Comment by dwillis** [comment]
How does asserting copyright over proposed legislation square with the U.S. Copyright Office's definition of "edicts of government", which says this:

```
Edicts of government, such as judicial opinions, administrative rulings, legislative enactments, public ordinances, and similar official legal documents are not copyrightable for reasons of public policy. This applies to such works whether they are Federal, State, or local as well as to those of foreign governments.
```

In what legal sense is proposed city legislation eligible for copyright assertion?

**Comment by JoshData** [comment]
@dwillis and I had a [long twitter thread](https://twitter.com/derekwillis/status/644993556864757761) about this.

Prior to enactment, these bills likely are protected by copyright law, just as say model laws and standards later incorporated by reference are, and @BenKallos could license them. If/when enacted, the copyright would likely vanish. (I am putting aside the question of whether restrictively licensing proposed laws is even ethical.)

There's a separate question of who holds the copyright, though. To the extent these bills are created as part of @BenKallos's job as city council member, there's an argument to be made that the copyright is held by the city (or the city council), which [is possible](https://law.resource.org/pub/us/case/reporter/F3/261/261.F3d.179.00-9011.00-9169.2000.html). In this case, @BenKallos wouldn't necessarily be in a position to license them in the first place. (Which is interesting because it would mean the public has even fewer rights to use the bills than where we are now with AGPL.)
