### ISSUE TITLE
Store proposed legislation in markdown, rather than plain text

### ISSUE THREAD

**Issue by benbalter** [BenKallos/legislation#4]
Adding some white space and a `.md` extension to the proposed legislation would allow them to render as human-readable HTML, rather than as raw text (which is rendered in a monospace font and flows off the edge of the screen). 

No substantive changes to the content or formatting would be necessary. In addition to adding a `.md` extension to each bill, numbered lists would require an extra newline (return), after each list item so as to be properly parsed as markdown.

**Comment by BenKallos** [comment]
Thanks @benbalter for the great advice. We are working to open up our legislation so that it is available in a variety of formats, however, without community support it is difficult to put the legislation up in the variety of formats requested. Great news is that you are welcome to convert our legislation to add white space and a .md extension and push those versions to our repo. Looking forward to your contributions!
